### ISSUE TITLE
Mac IDE Opens & Crashes Right After Installation

### ISSUE THREAD

**Issue by NanoSharkGames** [YoYoGames/Test-GameMaker-Bugs#65]
### Description

While installing or updating GameMaker on Mac, the IDE automatically launches & then crashes shortly after.

```
[12:20:39:380(6f8a)] LoadingState: UserLogin
[12:20:39:776(6f8a)] --------------------------------------------------------------------------------
[12:20:39:778(6f8a)] IDE Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/GameMakerStudio2-Beta'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1 enumerable, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetDirectories(String path)
   at YoYoStudio.User.User.MigrateSettingsFromLegacyAccount(String _id, String activeAccountDir)
   at YoYoStudio.User.User..ctor(String _email, String _loginName, String _id, String _sessionToken, String _publisher, Boolean _offline, String _accessToken, String _refreshToken, String _sso_accessToken, String _sso_refreshToken, String _seatType)
   at A.d.D(Boolean )
   at YoYoStudio.SplashScreen.SplashTick()
   at YoYoStudio.Plugins.MethodContainer.Call(Object[] _args)
   at YoYoStudio.Plugins.Command.Perform(Function _command, String _action, Object[] _parameters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.Command.execute(String _command, Object[] paramaters)
   at YoYoStudio.Plugins.Command.Perform(Function _command, String _action, Object[] _parameters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
```

When launching GameMaker directly, it does not result in a crash.

### Steps To Reproduce

Install GameMaker for the first time or install a GameMaker update on Mac, wait for installation to complete & pull up the GameMaker IDE window.

[ad628adc-4375-412f-8fbf-d7b91837f766](https://api.gamemaker.io/api/github/downloads/ad628adc-4375-412f-8fbf-d7b91837f766)

**Comment by YYDan** [comment]
I do note that your machine has an issue every GM startup with this error:

```
[12:45:48:944(745e)] LoadingState: InitDnD
[12:45:48:976(745e)] DnD: Installing gadgets from IDE
[12:45:49:8(745e)] DnD: Installing gadget failed: DnDCodeInput
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'constructor')
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at YoYoStudio.Core.Utils.YoYoActivator.<>c__DisplayClass2_0.<CreateInstance>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at YoYoStudio.Core.Utils.YoYoActivator.CreateInstance(Type _type)
   at YoYoStudio.GUI.Layout.LayoutManager.CreateGadget(XmlElement _xmlNode, LayoutInstanceID _ownerLayout)
   at YoYoStudio.GUI.Layout.LayoutManager.CreateGadgets(GUIBase _g, XmlElement _xmlNode, LayoutInstanceID _ownerLayout)
   at YoYoStudio.GUI.Layout.LayoutManager.CreateLayout(String _layoutID)
   at YoYoStudio.DnD.DnDGadget`1.ApplyLayout(String _layoutName)
   at YoYoStudio.DnD.Arguments.DnDCodeInput..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at YoYoStudio.DnD.DnDManager.InstallDnD(Assembly _assembly)
```

**Comment by YYDan** [comment]
Your first error will be system permissions due to the installer not having permission to modify files/folders in that /Users/Shared/location. Hopefully, you're all sorted already, but if not, please see https://help.gamemaker.io/hc/en-us/articles/360022953052 and this will show you how to fix all permission issues as best as we can.


The second issue is almost certainly https://github.com/YoYoGames/GameMaker-Bugs/issues/1628 and so has been fixed already in Aug releases (your report is obvs for an early Aug Beta).

I will close this old report now that I have investigated the info and given the answer here, trusting that all got fixed already for the August .1 release (certainly before .2).
